language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t egbeoso/react-test -f ./client/Dockerfile.dev ./client


script:
    - docker run -e CI=true egbeoso/react-test npm test

after_success:
    - docker build -t egbeoso/multi-client ./client
    - docker build -t egbeoso/multi-nginx  ./nginx
    - docker build -t egbeoso/multi-server  ./server 
    - docker build -t egbeoso/multi-worker  ./worker

    #push images to docker hub please log into docker cli

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push egbeoso/multi-client
    - docker push egbeoso/multi-nginx
    - docker push egbeoso/multi-server
    - docker push egbeoso/multi-worker


